### ISSUE TITLE
Dropdown Selected Value Different than What's Shown

### ISSUE THREAD

**Issue by EricPreventa** [LanarsInc/direct-select-flutter#10]
Getting a weird issue where the value in the dropdown list is not what's shown when clicked. 
Allow me to try and explain this weird issue. 

We have 2 fields - State and City. State has 2 options, and City has 2 options for each State (or 4 options total). 
State = ['MA', 'NH'] 
'MA'
['Boston', 'Cambridge']

'NH'
['Concord', 'Manchester']

If I click on MA in the first box, then I can click on either Boston or Cambridge on the second, this works fine. The issue is if I then change the first DirectSelectList to NH. The values show correctly in the second DirectSelectList, however once I click on them - for instance Concord - the value will in fact still show Boston.

I have this in my Drawer. So if I close my Drawer and re-open it builds correctly and shows the correct value - until I do the same thing again. 

It appears that it still holds its value and I believe this is a problem with the library itself. Has anyone seen this issue before?

**Comment by EricPreventa** [comment]
DirectSelectItem<String> getDropDownMenuItem(dynamic value)
	{
			return DirectSelectItem<String>(
					itemHeight: 56,
					value: value,
					itemBuilder: (context, value)
					{
						//print(value);
						return Text(value);
					});
	}

The value in itemBuilder(context, value) ends up showing the older previous value shown. Only way to correct this is if the entire widget is rebuilt. This shouldn't be the case.

**Comment by akhilpune** [comment]
I also have the same problem..

**Comment by EricPreventa** [comment]
> I also have the same problem..

Unfortunately due to the issue I wasn't able to resolve the problem. I switched back to just the typical drop down selector to solve my problem. Not as pretty, but function over looks always prevails.

**Comment by alexeypodolian** [comment]
Hello there

@EricPreventa Could you please provide full code example in order us to look at it more precisely?

**Comment by EricPreventa** [comment]
> Hello there
> 
> @EricPreventa Could you please provide the full code example in order us to look at it more precisely?

Hi @alexeylanars unfortunately I stopped using it about 8 months ago. So I don't have any code other than what was posted above. I'll defer to @akhilpune (as he's also having the same problem) to have him provide more of a code example.

**Comment by alexeylanars** [comment]
@EricPreventa Ok, thanks

@akhilpune Could you please provide the full code example?

**Comment by vizhan-lanars** [comment]
I have reproduced that bug.

**Comment by vizhan-lanars** [comment]
@EricPreventa @akhilpune 
Fixed on LanarsInc/direct-select-flutter@63687a0c966c86b3991de4dec032d2ba8f8ff9f5
