### ISSUE TITLE
Ability to customize the container

### ISSUE THREAD

**Issue by na2axl** [LanarsInc/direct-select-flutter#12]
Hi @LanarsInc,

Please can we have the ability to customize the DirectSelectContainer (especially the Container `decoration`)? To have for example, a custom background color instead of the default `scaffoldBackgroundColor`.

Thanks.

**Comment by iyatsouba** [comment]
Hi @na2axl . We've added optional decortion param to DirectSelectContainer since 1.0.5 :)
