### ISSUE TITLE
Is there a configuration to use tap

### ISSUE THREAD

**Issue by marvin-min** [LanarsInc/direct-select-flutter#13]
I'd like using tap instead of long press.  How can I handle the event?

**Comment by jamesmenera** [comment]
@marvin-min hey I have the same question as you. Have you found a solution for this yet? If so would you be willing to share with me?

**Comment by marvin-min** [comment]
> @marvin-min hey I have the same question as you. Have you found a solution for this yet? If so would you be willing to share with me?

Sorry, I haven't any solutions on this. Also did not dig deep.

**Comment by b-cancel** [comment]
I send this motion... @marvin-min and @jamesmenera 

right now for this great package to be actually usable, I'm having to make a little pop up come up If the user taps an invisible translucent gesture detector above this widget... but that is most definitely not ideal

**Comment by dungnv2602** [comment]
Any update on this? I came up with this beautiful UI package, and then feel really sad because it doesn't support pop up on tap.

**Comment by alexeylanars** [comment]
> Any update on this? I came up with this beautiful UI package, and then feel really sad because it doesn't support pop up on tap.

Hi :) 

No, we will support this packege in near future) 

We thought that open popup on single tap conflicts with the main idea of this package. But if you really need it we can think about it how to do it.

**Comment by alexeylanars** [comment]
> I second this motion... @marvin-min and @jamesmenera
> 
> right now for this great package to be actually usable, I'm having to make a little pop up come up If the user taps an invisible translucent gesture detector above this widget... but that is most definitely not ideal

As far as I know, there is a popup with tip if you just tap(not long tap) on item. Need to ckeck

**Comment by vizhan-lanars** [comment]
@marvin-min 
There is a DirectSelectList onUserTappedListener
