### ISSUE TITLE
Dynamic drag speed for both long and short lists

### ISSUE THREAD

**Issue by ibraheem-nt** [LanarsInc/direct-select-flutter#14]
I am using the selector for long lists (more than 80 items). What I had to do to support better navigation is to dynamically modify the drag speed multiplier from this:
https://github.com/LanarsInc/direct-select-flutter/blob/452bc6bebeb2f1828f3db0f35321f7f4a1e5afbe/lib/direct_select_container.dart#L236
To this:
`dragDy * (widget.dragSpeedMultiplier * (_currentList.items.length/11)));`

**Comment by vizhan-lanars** [comment]
@ibraheem-nt I guess you can achieve that by modifying the dragSpeedMultiplier parameter.
