### ISSUE TITLE
Usability Issues

### ISSUE THREAD

**Issue by b-cancel** [LanarsInc/direct-select-flutter#16]
**Enhancement**
This UX pattern is great
I would love to help shift to it
2 less steps for the user once they know how to use it

BUT first, we need to teach them how to use it
this means that
1. when the user taps the selection box it should also open up the drop-down "page"
2. additionally when that kind of page comes up it should also explain to the user the way it SHOULD be used (hold, drag, let go)
3. and that kind of page, since it was opened on tap it should allow one to select on tap
4. and of course since you are selecting on tap it should allow you to scroll but WITHOUT highlighting any item since that would be confusing

**Bug Fix**
Additionally, currently, if you tap long enough to trigger the animation to open up the page, but not long enough to "select" an item you are stuck with the page open with the options, but no way to close it or select an item... this should not happen

I will eventually fix this within a month or two for my own app as a nice little enhancement but it would be great if you would since you already know what you have done and would have an easier time adding anything else

**Comment by khoerling** [comment]
This advice is spot-on.  Direct Select is a very forward-thinking interaction that needs polish.  Wouldn't mind helping out when I've got time...

**Comment by vizhan-lanars** [comment]
@b-cancel 
Sorry, but described behaviour is out of widget idea. The purpose of this package is reduce a number of steps to select the option. 
BTW, on user short tap you can show pop up with a hint that user should use the long tap (there is the DirectSelectList onUserTappedListener).
