### ISSUE TITLE
How can we show the list of items on single press not long pressed?

### ISSUE THREAD

**Issue by umair-ilyas** [LanarsInc/direct-select-flutter#21]
This widget is working  perfectly on long press. But what if we want the same functionality on single pressed button. After pressing it single time list shows and we can scroll and choose respective items and show it back again.
Can we do that?

**Comment by ivanmercado9** [comment]
Were you able to solve the problem with the longpress? If you did, can you share the solution please.

**Comment by vizhan-lanars** [comment]
We thought that an open popup on single tap conflicts with the main idea of this package. 
There is a DirectSelectList onUserTappedListener to show a hint for a user.
