### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Work90210** [LanarsInc/direct-select-flutter#25]
Every time I try to click the UI to select an item in the list. I get the following error.

Null check operator used on a null value
The relevant error-causing widget was
DirectSelectContainer

Any help would be welcome. Thanks in advance

**Comment by vizhan-lanars** [comment]
Does the issue still relevant for you?

**Comment by Tokenizer94** [comment]
I have the same issue.
type 'List<DirectSelectItem<String>?>' is not a subtype of type 'List<DirectSelectItem<String>>' in type cast

**Comment by danhojin** [comment]
Same here,  I have the same error,

Expected a value of type 'List<DirectSelectItem<String>>', but got one of type 'List<DirectSelectItem<String>?>'

from a simple code, 

`
class HomePage extends StatelessWidget {
  final _cities = ['A', 'B', 'C'];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('direct_select_flutter'),
      ),
      body: DirectSelectContainer(
        child: Column(
          children: [
            DirectSelectList<String>(
              values: _cities,
              defaultItemIndex: 1,
              itemBuilder: (value) => DirectSelectItem<String>(
                value: value,
                itemBuilder: (context, value) => Text(value),
              ),
              focusedItemDecoration: const BoxDecoration(
                border: BorderDirectional(
                  bottom: BorderSide(color: Colors.black12),
                  top: BorderSide(color: Colors.black12),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
`

**Comment by 4amVim** [comment]
Switching to the previous version (`1.0.7`) and running with unsound null safety resolves the issue.

I suspect there was a typo while migrating to null-safety.

**Comment by Tokenizer94** [comment]
> 
> 
> Switching to the previous version (`1.0.7`) and running with unsound null safety resolves the issue.
> 
> I suspect there was a typo while migrating to null-safety.

But we can't switch to unsound null safety for just one library.

**Comment by 4amVim** [comment]
> But we can't switch to unsound null safety for just one library.
Well, depends on your use case right ? I did switch just for this library as it offers enough value. 

One weekend I'll sit and craft a PR to fix this ( I hope). I request you to have a look into the same, the library is extremely well written, and easy to read really!
P.S. Thanks Vizhan 😀😀

**Comment by elmissouri16** [comment]
same for me  i had this issue as well  `type 'List<DirectSelectItem?>' is not a subtype of type 'List<DirectSelectItem>' in type cast`

**Comment by vizhan-lanars** [comment]
Sorry fellas for the delay.
Will take a look soon.

**Comment by vizhan-lanars** [comment]
Please check version 1.1.1.
It looks fine from my side.

**Comment by 4amVim** [comment]
Yes! it works perfectly now, thank you. Should probably close this issue perhaps.
